Upgrade to Django 2.2.2 and Python 3
klee/old-klee-web pull request #128
Opened 2019-06-07 08:04 UTC by Denis-Gavrielov

Additionally solve all the vagrant provision errors.

2019-07-09 23:14 UTC, andronat requested changes

2019-07-09 23:14 UTC, andronat commented on src/klee_web/requirements.txt
> +django==2.2.2
We should allow minor releases. e.g. Django already moved to 2.2.3 which has security updates. As a later thought, we need to think on how to get notifications for new dependency releases. e.g. How would we know when to re-deploy klee-web?

2019-07-09 23:14 UTC, andronat commented on src/klee_web/requirements.txt
>  celery==3.1.23
Can we upgrade to latest celery?

2019-07-09 23:14 UTC, andronat commented on src/klee_web/frontend/models.py
> +    project = models.ForeignKey(Project, on_delete=models.CASCADE)
Merge this commit with the previous one.

2019-07-09 23:14 UTC, andronat commented on src/klee_web/frontend/models.py
> +    default_file = models.ForeignKey("File", on_delete=models.CASCADE, null=True, blank=True,
Maybe I'm wrong but if I get it right this means that when a File is deleted, the project is deleted too. Do we want this behavior?

2019-07-09 23:14 UTC, andronat commented on src/klee_web/requirements.txt
> +djangorestframework==3.9.4
Again we should allow minor releases.

2019-07-09 23:14 UTC, andronat commented on provisioning/roles/webdriver/tasks/main.yml
> +  become: yes
Could you provide some more info, on which specific package requires sudo and what is the error?

2019-07-09 23:14 UTC, andronat commented on src/klee_web/settings.py
> -    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
This line seems to be unrelated to this commit. Should be included somewhere else?

2019-07-09 23:14 UTC, andronat commented on src/klee_web/settings.py
> +GEOIP_PATH = os.path.join('geoip')
You don't need `os.path.join` anymore. I would suggest though to create an absolute path rather than a relative one like [this](https://stackoverflow.com/a/5137509).

2019-07-09 23:14 UTC, andronat commented on provisioning/vagrant.yml
> +      pip_executable: pip3
Merge this line into the previous commit.

2019-07-09 23:14 UTC, andronat commented on src/klee_web/requirements.txt
> +redis==2.10.6
Again we should allow minor versions.

2019-07-09 23:14 UTC, andronat commented on src/klee_web/frontend/views.py
> -from django.contrib.auth import login as django_login
This line should be included in the login/logout commit.

2019-07-09 23:14 UTC, andronat commented on src/klee_web/frontend/models.py
> +                                     blank=True,
If I'm not wrong, these are just format chances. Please include them into the commit that changed the `on_delete`.

2019-07-09 23:15 UTC, andronat commented
Excellent first iteration! Let's finish up with some minor issues here and there and we are ready to merge.

2019-07-10 09:53 UTC, Denis-Gavrielov commented on src/klee_web/frontend/models.py
> +    default_file = models.ForeignKey("File", on_delete=models.CASCADE, null=True, blank=True,
That is true, but it seems like that there is no way to delete the files on the website in first place. Do you believe it is still an issue? 
Also, alternatives would be using configurations like `PROTECT`, where I would need to handle the `ProtectedError` somewhere. Is that preferred?

2019-07-10 10:17 UTC, Denis-Gavrielov commented on src/klee_web/settings.py
> +GEOIP_PATH = os.path.join('geoip')
The absolute path was actually appended with the BASE_DIR variable.

Note: 
`BASE_DIR = os.path.dirname(os.path.dirname(__file__))` on line 19. 

However, keeping `GEOIP_PATH = os.path.join(BASE_DIR, 'geoip')` leads to the issue that when running the provisioning, the `Run Django South migrations` task within `provisioning/roles/web/tasks/deploy.yml` fails, because it expects the geoip folder to be on the same level as the klee_web folder. If I move the geoip folder out there, then as soon as the website is up and I load it I get the error 

`GeoIP2Exception at /`

`GeoIP path must be a valid file or directory.`.

I can bypass the error by either keeping two copies of the geoip folder (one within klee_web, and one on the same level as klee_web), or by changing the GEOIP_PATH to a relative path as I did in my commit. As I do not want to create unnecessary duplication I went with the above commit. 

Let me know if there is a smarter way to solve the issue or if you want me to have to geoip folders.

2019-07-10 12:36 UTC, Denis-Gavrielov commented on src/klee_web/settings.py
> +GEOIP_PATH = os.path.join('geoip')
Note: I have now changed `GEOIP_PATH = os.path.join('geoip')` to `EOIP_PATH = 'geoip'` for now.

2019-07-12 07:50 UTC, andronat requested changes

2019-07-12 07:50 UTC, andronat commented on src/klee_web/requirements.txt
> +django-bootstrap-form==3.4
Shouldn't this also be `3.4.*`?

2019-07-12 07:50 UTC, andronat commented on provisioning/roles/web/tasks/web.yml
> +- apt: name=python3.5-dev update_cache=yes state=present
Is there a reason we specifically bind to 3.5? Isn't there a `python3-dev` package that automatically resolves the latest available python 3 version?

2019-07-12 07:52 UTC, andronat commented on src/klee_web/frontend/models.py
> +    default_file = models.ForeignKey("File", on_delete=models.CASCADE, null=True, blank=True,
Let's keep it like that for now, but could you please add a TODO note above in case we want to revisit this in the future.

2019-07-12 12:15 UTC, andronat requested changes

2019-07-12 12:15 UTC, andronat commented on provisioning/roles/worker/tasks/deploy.yml
> +  pip: requirements={{ application_dir }}/requirements.txt virtualenv={{ worker_virtualenv }} virtualenv_python=python3.5
Change this to python3

2019-07-12 12:15 UTC, andronat commented on provisioning/roles/worker/tasks/python.yml
> +      - python3.5-dev
Change this to python3

2019-07-12 12:19 UTC, andronat approved these changes

2019-07-12 12:20 UTC, merged