Fixed coverage by removing import for gcovparse and creating modified gcovparse within /util
klee/old-klee-web pull request #198
Opened 2022-06-13 15:12 UTC by kt218

2022-06-13 19:32 UTC, ccadar requested changes
Thanks, left a couple of questions

2022-06-13 19:32 UTC, ccadar commented on src/klee_web/worker/utils/gcovparse.py
> +# A modified version of gcovparse available for python2.7
Quick questions: 

1) Why not take this from Python 3?

2) What is the license for this file?  It should be copied in the header.

2022-06-13 19:48 UTC, kt218 commented on src/klee_web/worker/utils/gcovparse.py
> +# A modified version of gcovparse available for python2.7
I've tried looking up the gcovparse library since it was causing type issues. I wasn't able to find anything, thus I used PyCharm's lookup defintion to find the .py within /usr/lib. Based of the file, I think it was written for python2 as map and filter no longer return lists in python3.

2022-06-13 21:35 UTC, ccadar commented on src/klee_web/worker/utils/gcovparse.py
> +# A modified version of gcovparse available for python2.7
Isn't this what you need?
https://gcovr.com/en/stable/

2022-06-13 21:54 UTC, kt218 commented on src/klee_web/worker/utils/gcovparse.py
> +# A modified version of gcovparse available for python2.7
I think that's a different library but I'm not too sure. From looking at the docs, I got the idea that it was a command line tool, thus, I avoided using it.

2022-06-13 21:58 UTC, ccadar commented on src/klee_web/worker/utils/gcovparse.py
> +# A modified version of gcovparse available for python2.7
I would assume they also have a library, but I haven't looked. 
In any case, I'm fine to use something else, but we should document the license.

2022-06-13 22:22 UTC, kt218 commented on src/klee_web/worker/utils/gcovparse.py
> +# A modified version of gcovparse available for python2.7
Trying to follow the link on https://package.wiki/gcovparse, the github repo returned 404. The license for gcovr is found in https://github.com/gcovr/gcovr/blob/master/LICENSE.txt. However, looking through the [parser](https://github.com/gcovr/gcovr/blob/master/gcovr/gcov_parser.py) they have is completely different in code.

2022-06-16 12:32 UTC, kt218 commented on src/klee_web/worker/utils/gcovparse.py
> +# A modified version of gcovparse available for python2.7
I've added the metadata of gcovparse to the header of gcovparse.py

2022-06-16 13:10 UTC, ccadar approved these changes

2022-06-16 13:10 UTC, ccadar commented
Thanks, @kt218 , with the license clearly acknowledged, we can merge this now.

2022-06-16 13:11 UTC, merged